### ISSUE TITLE
Streaming bug?

### ISSUE THREAD

**Issue by zeluis9** [balderdashy/sails-mysql#275]
Hi guys. I think I've found a bug in sails-mysql.

When executing: 

    MyModel.stream({ id: my_awesome_ids_array}).pipe(res);

where `res` is the response object on a controller method, I got this:

    TypeError: sql.selectQuery is not a function
        at __STREAM__ (/home/ze/NodeProjects/cloudsales.wms.bo/node_modules/sails-mysql/lib/adapter.js:904:25)

This only works with `req.socket.emit` instead of `res`?

**Comment by particlebanana** [comment]
Fixed in #264 should be published sometime today.

**Comment by zeluis9** [comment]
Sorry @particlebanana , I didn't knew that. Keep up the good work! :+1:

**Comment by particlebanana** [comment]
@zeluis9 if you could test it out using master before I publish that would be great! I don't think the way the stream interface works you can just pipe the results but I could be wrong, I haven't tested that interface in a while! Let me know what the end result it.

**Comment by zeluis9** [comment]
Ok @particlebanana . I will test that! Wait for my feedback :+1:

**Comment by zeluis9** [comment]
The current version doesn't crash the process, but I'm still unable to pipe it to the response object, like you said. Is it something we could work in, right? Could you give some insights on this?

BTW, when I run the tests:

![captura de ecra de 2016-01-29 16 40 37](https://cloud.githubusercontent.com/assets/11177829/12681567/11e54be0-c6a7-11e5-98da-77d4bfe24762.png)

**Comment by particlebanana** [comment]
Hey @zeluis9 can you post an example project? The `.pipe` function works when I test it using the master version of sails-mysql.

**Comment by zeluis9** [comment]
Ok @particlebanana wait for my feedback

**Comment by zeluis9** [comment]
Hi @particlebanana . Incredibly, on a newly created project, it works! Must be something wrong with my project. We can close this :+1:  :+1:
